### ISSUE TITLE
Option "callMeNow" is not documented

### ISSUE THREAD

**Issue by jehon** [BrodaNoel/duix#11]
But is it a easy to understand name ?
See a beginning of discussion in #10

**Comment by jehon** [comment]
I propose "fireImmediately" instead
Or withLastValue ?

**Comment by BrodaNoel** [comment]
I agree about renaming it to `fireImmediately`, and releasing a version `2.0.0` with it (and with the `deepEqual` change)

**Comment by BrodaNoel** [comment]
@jehon We have a breaking change (the "call only when value actually changed") on `master` branch right now, we could make this small change (just renaming to `fireImmediately` and adding it on the README) and then deploy `v2.0.0`.

Let me know if you want to do this change, if not, I can do it.
