### ISSUE TITLE
Should have an automated test

### ISSUE THREAD

**Issue by jehon** [BrodaNoel/duix#12]
Would travis be ok for you? 

=> If yes, I can implement it, but you need to enable the integration
If no, tell me which one to use :-)

**Comment by BrodaNoel** [comment]
I just activated it.

`https://travis-ci.com/BrodaNoel/duix.svg?branch=master`

**Comment by jehon** [comment]
The config has just been merge in #10 (just seen it, forgot to mention it - sorry)
